project:
  type: book
  output-dir: _book
  render:
    - "*.qmd"
    - "!Local Only/"

book:
  title: "Book of Workshops"
  #downloads: [pdf, epub]
  sharing: [linkedin]
  repo-url: https://github.com/ysph-dsde/Book-of-Workshops
  repo-actions: edit
  search: true
  bread-crumbs: false
  reader-mode: true
  sidebar:
    style: "docked"
  date: 04/13/2025
  date-format: long
  chapters:
    - index.qmd
    - part: Workshops/Git-and-GitHub/git-github-index.qmd
      chapters: 
        - Workshops/Git-and-GitHub/Pages/git-github-what-is.qmd
        - Workshops/Git-and-GitHub/Pages/git-github-setup.qmd
        - Workshops/Git-and-GitHub/Pages/git-github-detailed-walkthrough.qmd
        - Workshops/Git-and-GitHub/Pages/git-github-more-to-come.qmd
    - part: Workshops/Intro-to-Programming-in-R/programming-r-index.qmd
      chapters: 
        - Workshops/Intro-to-Programming-in-R/Pages/programming-r-worked-through-example.qmd
        - Workshops/Intro-to-Programming-in-R/Pages/programming-r-more-to-come.qmd
    - part: Workshops/Code-Smarter-Not-Harder/ai-coding-index.qmd
      chapters: 
        - Workshops/Code-Smarter-Not-Harder/Pages/ai-coding-worked-through-example.qmd
    - part: Workshops/Data-Visualization-with-ggplot2/visualization-index.qmd
      chapters: 
        - Workshops/Data-Visualization-with-ggplot2/Pages/visualization-worked-through-example.qmd
        - Workshops/Data-Visualization-with-ggplot2/Pages/visualization-more-to-come.qmd
  page-footer:
    background: light 
    left: "This site was built on a ysph-dsde.github.io page. It was rendered using Quarto (v 1.6.3) and theme [bookup-html](https://github.com/juba/bookup-html/tree/main)." 
    center: "</ul><div style='margin-top: 10px;'>Have thoughts about this resource?</br>Yale affiliates, provide feedback <a href='https://forms.office.com/Pages/ResponsePage.aspx?id=u76M3Tkh-E20EU4-h6vrXH-TvKDg8gZHqoE3FAMavy5UMjhSTjVOWjQ0MkFIM0hDS0pVQ0tZN1kzMi4u'>here</a>.</br>Non-affiliates, provide feedback <a href='https://forms.office.com/Pages/ResponsePage.aspx?id=u76M3Tkh-E20EU4-h6vrXH-TvKDg8gZHqoE3FAMavy5URFBRQ1ZVUFlFVEY0MElSNTlSSzJTWkhXNS4u'>here</a>.</div><ul class='footer-items list-unstyled' style='display:none;'>"
    right: 
      - icon: globe
        href: https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/
      - icon: github
        href: https://github.com/ysph-dsde
      - icon: linkedin 
        href: https://www.linkedin.com/showcase/public-health-data-science-and-data-equity-at-yale/
      - icon: envelope 
        href: mailto:admin.dsdeysph@yale.edu
      - text: "(203) 737-8644"


hypothesis: true

format:
  html:
    include-in-header: 
      - _includes/google_analytics.html
      - _includes/definition_popup.html
    header-includes:
      - <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
      - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/devicon/2.14.0/devicon.min.css">
    html-math-method: katex
    toc: true
    toc-depth: 3
    number-sections: false
    unnumbered: true
    callout-appearance: default
    theme:
      light: 
        - _styles/bookup/bookup.scss
      dark: 
        - _styles/bookup/bookup.scss
        - _styles/bookup/bookup_dark.scss
    filters: 
      - _styles/bookup/embed-fonts.lua

editor: source

markdown: 
  keep-md: true
  editor_options: 
    chunk_output_type: console


