project:
  type: book

book:
  title: "Book of Workshops"
  #downloads: [pdf, epub]
  sharing: [linkedin]
  repo-url: https://github.com/ysph-dsde/Book-of-Workshops
  repo-actions: edit
  search: true
  bread-crumbs: false
  reader-mode: true
  sidebar:
    style: "docked"
  date: 04/13/2025
  date-format: long
  chapters:
    - index.qmd
    - part: Git-and-GitHub/index.qmd
      chapters: 
        - Git-and-GitHub/Pages/git-github-what-is.qmd
        - Git-and-GitHub/Pages/git-github-setup.qmd
        - Git-and-GitHub/Pages/git-github-overview.qmd
    - part: Data-Visualization-with-ggplot2/index.qmd
      chapters: 
        - Data-Visualization-with-ggplot2/Pages/visualization-more-to-come.qmd
        - Data-Visualization-with-ggplot2/Pages/visualization-worked-through-example.qmd
  page-footer:
    background: light 
    left: "This site was built on a ysph-dsde.github.io page. It was rendered using Quarto (v 1.6.3) and theme [bookup-html](https://github.com/juba/bookup-html/tree/main)." 
    center: "Have thoughts about this resource? Yale affiliates, provide feedback [here](https://forms.office.com/Pages/ResponsePage.aspx?id=u76M3Tkh-E20EU4-h6vrXH-TvKDg8gZHqoE3FAMavy5UMjhSTjVOWjQ0MkFIM0hDS0pVQ0tZN1kzMi4u). Non-affiliates, provide feedback [here](https://forms.office.com/Pages/ResponsePage.aspx?id=u76M3Tkh-E20EU4-h6vrXH-TvKDg8gZHqoE3FAMavy5URFBRQ1ZVUFlFVEY0MElSNTlSSzJTWkhXNS4u)."
    right: 
      - icon: globe
        href: https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/
      - icon: github
        href: https://github.com/ysph-dsde
      - icon: linkedin 
        href: https://www.linkedin.com/showcase/public-health-data-science-and-data-equity-at-yale/
      - icon: envelope 
        href: mailto:admin.dsdeysph@yale.edu
      - text: "(203) 737-8644"


hypothesis: true

format:
  bookup-html:
    html-math-method: katex
    toc: true
    toc-depth: 3
    number-sections: false
    unnumbered: true
    callout-appearance: default

editor: source

markdown: 
  keep-md: true
  editor_options: 
    chunk_output_type: console


